"Sledece sto bih mogao da unesem trebalo bi da bude mozda foldovanje

""call ucompleteme#Setup()

"Ovo bi trebao da bude deo koda koji se odnosi na Vundle
"umesto ovog koda za linux
"set rtp+=~/.vim/bundle/Vundle.vim
"call vundle#begin()
"treba da stoji
"set rtp+=~/vimfiles/bundle/Vundle.vim/
"let path='~/vimfiles/bundle'
"call vundle#begin(path)

"////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
set nocompatible              " be iMproved, required
filetype off                  " required

" u slucaju ako je window onda nasetuj ove parametre
if has("win32") || has("win16")
	" set the runtime path to include Vundle and initialize
	" C:\Vim\vimfiles\bundle\Vundle.vim\"
	"set rtp+=~/vimfiles/bundle/Vundle.vim/
	set rtp+=C:/Vim/vimfiles/bundle/Vundle.vim/
	"let path='~/vimfiles/bundle'
	let path='C:/Vim/vimfiles/bundle'
" ako nije nasetuj ove  (tj za Linuxx i ostale platforme)
else
	set rtp+=~/vimfiles/bundle/Vundle.vim/
	let path='~/vimfiles/bundle'
endif
call vundle#begin(path)

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'

"EasyMotion
Plugin 'EasyMotion'

" plugin for autocomplite
Plugin 'ctrlp.vim'

"File system tree
Plugin 'The-NERD-tree'

"Tag bar - source code browse
Plugin 'Tagbar'

"Commenatari
Plugin 'The-NERD-Commenter'

"snippet
Plugin 'snipMate'

"trebalo bi da mi nudi argumente klase i sl ali ne radi
"Plugin 'javacomplete'

"dovrsava granicnike
Bundle 'Raimondi/delimitMate'

"dovrsava granicnike - pravio je problem da ne mogu da unosim text u CTRL+f
"modu
""Plugin 'AutoClose'

"youcompleteme
"Plugin 'ucompleteme'

"proba cscope-a - nesto ovo ne sljaka tj izgleda da mora rucno da se instalira pa da se napravi fajl pa tek onda da mu se pristupa. a i ovo je nominalno pravljeno za Linux
"Plugin 'cscope-menu'

"ovo je plugin koji ce da koristi cscope...valjda
"tek kada testiram i probam ovaj plugin onda cu ga komitovati
""Plugin 'hari-rangarajan/CCTree'

"pokusaj da prikaze msve markera"
Plugin 'kshenoy/vim-signature'

"dodata za komunikaciju za Git-om"
Plugin 'fugitive.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin from http://vim-scripts.org/vim/scripts.html
"Plugin 'L9'
" Git plugin not hosted on GitHub
"Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
"Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
"Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Avoid a name conflict with L9
"Plugin 'user/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
" required
call vundle#end()

"poenta leader-a je da niz komandi nesto znaci a ne kombinacija tj ne moraju
"tasteri istovremeno da se pritisnu!!!!!!!!!!!!!!!"
let mapleader = "\<Space>"

 " required
filetype plugin indent on
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
"
" Put your non-Plugin stuff after this line
"////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
"set nocompatible
"source $VIMRUNTIME/vimrc_example.vim
"source $VIMRUNTIME/mswin.vim
"behave mswin
filetype plugin on

"iskljucivanje back up fajlova
"no backup files
set nobackup       
"only in case you don't want a backup file while editing
set nowritebackup  
"no swap files
set noswapfile     


"otvaranje quickfix prozora
map <F1> :copen 5<CR>
map <F1><F1> :cclose<CR>

" pozivanje nerdtree-ja
map <F2> :NERDTreeToggle<CR>

" kretanje kroz otvorene fajlove (bafere)
nmap <F3> :bp<CR>
nmap <F4> :bn<CR>

" pozivanje tagova fajla (pojednostavljena verzija ctags) 
nmap <BS> :TagbarToggle<CR>

" u gVim-u su ctrl pgUp i pgDwn za kretanje kroz tab-ove
map <F8> <C-w>T
map <F8><F8> :tabclose<CR>

":tp predhodni, :ts nudi sve, :tn ide na sledecu definiciju funkcije"
map <F5> :ts<CR>

"da se gasi nohlsearch 
map <F9> :nohlsearch<CR>

" da ne moram da razlikujem prave redove od redova na ekranu
nnoremap j gj
nnoremap k gk

"unos i brisanje praznih redova
" Ctrl-j/k deletes blank line below/above, and Alt-j/k inserts.
" brise gornji ili donji red ako su prazni
nnoremap <silent><C-j> m`:silent +g/\m^\s*$/d<CR>``:noh<CR>
nnoremap <silent><C-k> m`:silent -g/\m^\s*$/d<CR>``:noh<CR>
" unosi novi red ispod ili iznad
nnoremap <silent><A-j> :set paste<CR>m`o<Esc>``:set nopaste<CR>
nnoremap <silent><A-k> :set paste<CR>m`O<Esc>``:set nopaste<CR>

"bad habit breaking - ostavicu za sada da se koristi mis...
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

"da ne bih brisao sa backsapce i delete
inoremap <BS> <Nop>
inoremap <Del> <Nop>

"font i velicina font-a.PAZI!!!!!!!!!!!nisam siguran da li ovaj font postoji na Linux-u tj da li ce ova komanda praviti problem kada se vim pokrene na Linux-u
set guifont=Consolas:h16
"ovo se unosi kako mi se ne bi brisao history kada se krecem medju baferima a
"mislim i da necu morati da svaki cas snimam fajl kad zelim da predjem na
"drugi
set hidden
" prica oko tabova... jos mi nije jasna...
"set tabstop=4
"set softtabstop=4
"set expandtab

"na ovaj nacin se koriste tabovi za uvlacenje i to tabovi sirine 4.iz nekog
"razloga ja od starta nisam tako koristio ali ovako cu koristi naposlu jer se
"u IngeDev-u koriste takva uvlacenja!
set shiftwidth=4
set tabstop=4

" broj redova
set number

" indending
set cindent

"upaliti syntax highlighting
syntax on

" highlighting dok kucam pattern
set hlsearch

" linija u kojoj je kursor je selektovana
set cursorline

" automatski se trazi rec i selektuje dok kucam pattern
set incsearch

"upali mogucnost folding-a
set foldmethod=syntax

" statusna linija  (sa puno podataka) - mozda cu ovu liniju izmeniti i
" iskoristiti vim airline plugin???
set laststatus=2
set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P

"na Windows-u mi nije prihvatao <ESC>!!!!!!
"RADIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII!!!!!!!!!!!!!!!!!!
imap jj <c-[>
" nastavim na kraju samo pritisnem ff
imap ff jjA
" da izbirsem poslednji rec ne izlazeci iz insert moda
imap dd <C-w>
" da izbirsem poslednji red ne izlazeci iz insert moda - stavicu vv posto mi je s blizu d pa cu cesto brisati ceo red umesto reci i obratno
imap vv <C-u>

" naravno ulazi ulazi donjih mapiranja z registar ce biti zauzet
" kopiranje reci ispod kursora
"iako sam uveo da se ne pretabava register ipak ni ovo nije losa opcija
nmap <Leader>r viw"xy
" paste reci ispod kursora
nmap <Leader>f viw"xp

"kada otkucam {} pozicionira me u novom redu sa uvucenim tabom izmedju {}
imap {} {}jji<CR>jjko 

"pozivanje easymotion plugin-a!!!!!
"trazenje reci unapred
"/\<Space>
""nmap ss \\w
nmap ss <Space><Space>w
"trazenje reci unazad
"nmap aa \\b
nmap aa <Space><Space>b

"This will check the current folder for tags file and keep going one directory up all the way to the root folder. SO you can be in any sub-folder in your project and it'll be able to find the tags files:
set tags=./tags;/

"F7 ce da mi otvori prozor veritkalno a F6 ce da mi otvori prozor horizontalno!!!!!!!!!!!!!!
"map <F7> :vsp <CR>:exec("tag ".expand("<cword>"))<CR>
" mislim da je dovoljan samo ovaj jedan donji poziv pa cu kasnije okrenuti da
" split...ili mi pak uopste nije potreban ovaj shortcut...jednostavno cu
" zapamtiti da pre samog poziva definicije pozovem novi prozor..."
map <F6> <C-w><C-]>

"misilm da cu i ovaj shotrcut moci da ickljucim...<C-w><C-c> zatvara otvoreni window a :bd zatvara i brise bafer i list-e otvorenih bafera.ako pak navedem :bd! onda ce da se nece snimiti izmene!i jos opasnija opcija :bw - onda se i brise bafer iz vim-a i fajl sa fajl sistema!"
map <A-q> <C-w><C-c>

"ovo je put do csope
set csprg=d:\Projekti\vim\cscope.exe
"mislim da cu zadrzati ovaj quickfix
set cscopequickfix=s-,c-,d-,i-,t-,e-,g-,f-

"napred mislim da ne koristim ovaj shortcut...mada bi on vazio za bilo koje
"koriscenje quickfix-a...neka ga za sada...mada mi se cini da za csope za sada
"koristim samo F10...ono sto moram da uradim za generisanje csope-a je spisak
"foldera (fajlova) za koje ne treba generisati lokacije (test folder kao
"i header-i)
map <F12> :cn<CR>
"nazad
map <F12><F12> :cN<CR>

"pomeranje granica prozora
map <Up> :1winc +<ENTER>
map <Down> :1winc -<ENTER>
map <Left> :1winc <<ENTER>
map <Right> :1winc ><ENTER>

"mozda bih ipak mogao da zapamtim sve ove skracenice...videcu tokom daljeg
"rada
         ""'s'   symbol: find all references to the token under cursor
   " nmap <C-\>s :cs find s <C-R>=expand("<cword>")<CR><CR><C-o>
   nmap <F10> :cs find s <C-R>=expand("<cword>")<CR><CR><C-o>
	"   'g'   global: find global definition(s) of the token under cursor
    nmap <C-\>g :cs find g <C-R>=expand("<cword>")<CR><CR><C-o>	
	"   'c'   calls:izbacuje sve pozive ove funkcije tj na kojim se sve mestima poziva
	""nmap <F10> :cs find c <C-R>=expand("<cword>")<CR><CR><C-o>
	    nmap <C-\>c :cs find c <C-R>=expand("<cword>")<CR><CR><C-o>
	"   't'   text:   find all instances of the text under cursor
    nmap <C-\>t :cs find t <C-R>=expand("<cword>")<CR><CR><C-o>	
	"   'e'   egrep:  egrep search for the word under cursor
    nmap <C-\>e :cs find e <C-R>=expand("<cword>")<CR><CR><C-o>	
	"   'f'   file:   open the filename under cursor
    nmap <C-\>f :cs find f <C-R>=expand("<cfile>")<CR><CR><C-o>	
	"   'i'   includes: find files that include the filename under cursor
   nmap <C-\>i :cs find i ^<C-R>=expand("<cfile>")<CR>$<CR><C-o>
	"izbacuje sve funkcije koje poziva ova funkcija
	""nmap <C-\>d :cs find d <C-R>=expand("<cword>")<CR><CR><C-o>
	"iz nekog razloga moraju ovde da se dodaju dva CTRL-o-a... ne znam zasto nece da izadje sa jednim
	""nmap <F11> :cs find d <C-R>=expand("<cword>")<CR><CR>	

"svaki put kada se promeni fajl automatski se osvezi
set autoread

"OVAJ SKUP KOMANDI BI TREBAO DA SE NADJE U MOM PRVOM SKRIPTU POSTO MORAM UVEK POSEBNO PONAOSOB DA IH UNESEM KADA UDJEM
":cs add d:\Ingenico\Projects\IngeDev7\cscope.out d:\Ingenico\Projects\IngeDev7 - RELATIVNA PUTANJA ODAKLE TREBA DA POCNU DA SE PRIMENJUJU PODACI IZ SAMOG CSCOPE.OUT FAJLA!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

"ovo donje setovanje ne znaci puno za gvim ali deluje al iza obican vim znaci!!!!!!!!!!!!!"
set background=dark
colorscheme desert

"ovo je dodatak za smestanje swap fajlova
set directory=.,$TEMP

"zatvaram fajla ali se ne zatvara prozor - kaze predji na sledeci bafer i zatvori poslednji koji je bio otvoren (alternativni)
"cini mi se da cu ipak preci na :bd - zatvaranje trenutnog bafera!
nnoremap <C-c> :bp\|bd #<CR>

"ocekujem da mi ne radi resize...
set noea

"neka dodatna stelovanja koja zavise od OS"
"setovanje da mi leader bude space

" u slucaju ako je window onda nasetuj ove parametre
if has("win32") || has("win16")
"poziv novog vimrc fajla!!!verovatno ce morati drugaciji poziv na linux-u???
"mozda preko $MYVIMRC
map <Del> :source c:\vim\_vimrc<ENTER>:nohlsearch<ENTER>
" otvori vimrc fajl. mozda je teze zapamtiti ali sam postavio na q jer mi je
" dalje za dohvatanje a ostavio bih home raw za nesto prece
nnoremap <Leader>q :e c:\vim\_vimrc<ENTER>
" java snippet-i. takodje prica kao i gore"
nnoremap <Leader>w :e C:\Vim\vimfiles\bundle\snipMate\snippets\java.snippets<ENTER>
" c snippet-i. takodje prica kao i gore"
nnoremap <Leader>e :e C:\Vim\vimfiles\bundle\snipMate\snippets\c.snippets<ENTER>

" ako nije nasetuj ove  (tj za Linuxx i ostale platforme)
else
endif
" testiranje novim mogucnosti"
""vmap v <Plug>(expand_region_expand)
""vmap <C-v> <Plug>(expand_region_shrink)
"ovo bi trebalo da je vrhunska fora - kada nesto selektujem pa onda kopiram
"negde ostaje mi u clipboard-u ono sto sam prvo kopirao"
" vp doesn't replace paste buffer
" radi!!!!!!!!!!!!!savrseno!!!!!!!!!!!!"
function! RestoreRegister()
  let @" = s:restore_reg
  return ''
endfunction
function! s:Repl()
  let s:restore_reg = @"
  return "p@=RestoreRegister()\<cr>"
endfunction
vmap <silent> <expr> p <sid>Repl()
" ovde bi trebalo da je search and replace"
"takodje radi!!!!!!!!!!stravica!!!!!!!!!!!!"
vnoremap <silent> s //e<C-r>=&selection=='exclusive'?'+1':''<CR><CR>
    \:<C-u>call histdel('search',-1)<Bar>let @/=histget('search',-1)<CR>gv
omap s :normal vs<CR>

" selektujem tekst koji sam upravo paste-ovao"
" dobra fora!!!!!!!gv takodje selektuje poslednje selektovan tekst - radi sa
" malim v"
noremap gV `[v`]

" copy and paste in system clipboard
"takodje radi vrhunski"
vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P

"snimanje fajla 
nnoremap <Leader>s :w<CR>

" Build the closest project to the current file with ant or maven
map <leader>b :call Build(0)<ENTER>
"map <leader>clb :call Build(1)<ENTER>:call Build(0)<ENTER>
" ovako pocinje funkcija
function! Build(clean)
	" u l.dir se smesta apsolutna do ovog fajla gde je pozvana ova funkcija"
	" % je trenutni fajl
	" :p apsolutna putanja
	" :h dodaje i ime fajla na kra
	" :t skida samo posledjni nivo tj ime fajl
	" :e skida ekstenziju poslendje fajla
	let l:dir = expand('%:p:h')
	" u windows-u je granicnik izmedju fajlova \ a posto je to u vimscript-u
	" escp seq mora da se escape-uje. na linux-u je potrebno postaviti samo
	" jedan granicnik /
	" . konkatenacija
	let l:pom = l:dir . "\\pom.xml"
	" da li postoji ovaj fajl filereadable
	while ! filereadable(l:pom)
		let l:dir = fnamemodify(l:dir, ':h')
		if 1 == strlen(l:dir)
			" ovako se prikazuje poruka na komandnoj liniji"
			echo "Could not find pom.xml, build.xml, build.gradle, or settings.gradle"
			return
		endif
		let l:pom = l:dir . "\\pom.xml"
		""echo l:pom
	endwhile

	echo "Pozicija pom.xml fajla je " . l:pom
	let l:rez = l:dir . "\\build_res.txt"
	echo "Ovde smestam rezultat " . l:rez
	"ovaj if mi za sada ne treba ali cu ga ostviti da bih znao za kasnije kako
	"treba da se radi.trenutno je dobro zato sto mi se svi rezultati kaleme
	"jedan na drugi ali cu kasnije mozda hteti da stavim neki filtar i da mi
	"se prikazuju samo odredjeni rez pa su mozda morati da napustim read..ali
	"za sada je ok!!!!!!!!!!!sta vise.savrseno je!!!!!!!!!
	" ovaj link pogledati da vidim zasto mi ne stima klasican poziv externog
	" programa - http://vim.wikia.com/wiki/Execute_external_programs_asynchronously_under_Windows
	if filereadable(l:pom)
		"nakon make se poziva ovaj string pa argumenti koje sam naveo iza
		"samog poziva u exe funkciji pa shellpipe i errfile"
		""set makeprg=mvn\ -q\ -e\ compile
		"ako zelim sistemskoj promenljivoj da dodelim string vrednost koristicu
		"let i &.izgleda da set smatra" kao nesto specijalno.cini mi se da se
		"smatra pocetkom komentara
		""set makeprg=mvn\ compile
		""let &makeef=l:rez
		" ovo dole su opcije koje se koriste za pipe-ing.kao s se uzima makeef.
		""shellpipe=>%s 2>&1 
		echo &makeef
		set efm=
					\%W[WARNING]\ %f:[%l\\,%c]\ %m,
					\%E[ERROR]\ %f:[%l\\,%c]\ %m,
					\%C\ %#symbol:\ %.%#\ %m,
					\%Z\ %#location:\ %.%#,
					\%C[ERROR]\ symbol:\ %.%#\ %m,
					\%Z[ERROR]\ location:\ %.%#,
					\%C[ERROR]\ %#required:\ %#%m,
					\%Z[ERROR]\ found:\ %#%m,
					\%Z\ %#found:\ %#%m,
					\%-Z%.%#,
					\[ERROR]\ %f:[%l]\ %m,
					\%-G%.%#,
			let l:args = "-f " . l:pom 
	endif

	""let l:bilduj = l:args
	""exe l:bilduj
	"exe komanda izvrsava sve sto hocu na komandnoj liniji.znaci kao da sam
	"pritisuno :komanda<enter>. sa exe samo unesem exe komanda"
	"pozicioniram se u fodler gde treba da pokrenem pom.xml"
	exe "cd " . l:dir
	echo "Ovde izvrsavam mvn komandu"
	exe "pwd"
	exe "e " . l:rez
	" read cita rezulta komande i smesta ispod kursora!!!!!!!!!!!!!
	exe "read !mvn compile " . l:args
	"cini mi se da moze i execute umesto exe
	"ova ko se zavrsava funkcija
endfunction
